# Generated by Django 2.2 on 2021-05-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVShow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
