# Generated by Django 2.2 on 2021-05-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVShow_app', '0002_shows_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
